Support environment variables in global job tags
jenkinsci/datadog-plugin pull request #190
Opened 2021-03-22 22:31 UTC by luisgonzalex

### What does this PR do?

Add support for environment variables in global job tags as per [Issue 54](https://github.com/jenkinsci/datadog-plugin/issues/54)

### Description of the Change

There was no support for env vars in the global job tags section previously. There are two cases. 
1. Freestyle jobs
    - These jobs will be run on master, so we can just use the `envVars` that is apart of the current build. 
2. Pipeline jobs
    - These jobs are run on virtual executors, we can use `EnvVars.masterEnvVars` to get master's env vars.
    - They can also be run on different agents, but this needs to be setup properly and tested manually. 
### Alternate Designs

### Possible Drawbacks

### Verification Process

1. Configure env variables and global job tags on master accordingly. 
2. Configure a freestyle/pipeline project. 
3. Build the project
4. Observe that global job tags are applied correctly. 

### Additional Notes

### Release Notes

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

2021-03-24 09:00 UTC, FlorianVeaux requested changes
Great PR and great testing 👏 

> This only supports env variables that were defined on the master jenkins agent. But this seems to be fine and more practical than using the env vars on the agent(s).

Let's add a comment on the jenkins UI and on the ReadMe that explains that env vars are supported for global tags and global job tags but that they refer to env vars of the controller (i.e master).

2021-03-24 14:56 UTC, FlorianVeaux approved these changes

2021-03-24 15:22 UTC, merged

2021-04-07 09:58 UTC, sukanyasuresh commented
Hi @luisgonzalex 
I am currently using the latest version of this plugin and for some reason, I am not able to get the actual value for the env variable substituted.  
This is my value configured for the global job name tags:

jobA, label:$LABEL

The value of this tag is always _label

What am I missing here?

2021-04-07 15:21 UTC, luisgonzalex commented
Hi @sukanyasuresh 
Couple of things you may be missing. 
- Make sure that the env var `LABEL` is defined in your shell resource file. It should be defined on the same machine that is running the jenkins app. 
- Another issue may be defining the env variable after you have initiated the jenkins application. You may want to restart jenkins and run `source ~/path/to/shell_resource_file` so your shell has the newly defined env vars. 

Hope this helps!